import uuid
from datetime import datetime
from sqlalchemy import String, Integer, Text, DateTime, func, ForeignKey, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from app.core.database import Base


class TeamWeeklyRecap(Base):
    """An AI-generated short blurb per team, one row covering an ENTIRE
    league's week in a single LLM call (not one call per team -- see
    team_recap_service.py's own docstring for why). One row per
    (league_id, week, year), same upsert-on-regenerate shape as
    CommissionerDigest -- auto-generated by the scheduler once a week
    goes final (Dashboard AI Summaries initiative), with the same
    commissioner-triggered manual endpoint as a fallback if the
    scheduler pass ever fails or a commissioner wants a fresh take."""
    __tablename__ = "team_weekly_recaps"
    __table_args__ = (
        UniqueConstraint("league_id", "week", "year", name="uq_team_weekly_recap_league_week_year"),
    )

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    league_id: Mapped[str] = mapped_column(String, ForeignKey("leagues.id"), nullable=False, index=True)
    week: Mapped[int] = mapped_column(Integer, nullable=False)
    year: Mapped[int] = mapped_column(Integer, nullable=False)
    # Plain text, one short blurb per team, same "no markdown, gets
    # displayed as-is" convention as CommissionerDigest.content.
    content: Mapped[str] = mapped_column(Text, nullable=False)
    # Nullable + no cascade, same reasoning as CommissionerDigest.generated_by
    # -- None here specifically means "the scheduler generated this",
    # not "an unknown user did".
    generated_by: Mapped[str | None] = mapped_column(String, ForeignKey("users.id"), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
