import uuid
from datetime import datetime
from sqlalchemy import String, Integer, Text, DateTime, func, UniqueConstraint
from sqlalchemy.types import JSON
from sqlalchemy.ext.mutable import MutableList
from sqlalchemy.orm import Mapped, mapped_column
from app.core.database import Base


class WeeklyTopPlayersSummary(Base):
    """AI-generated recap of the week's best-performing NFL players,
    ranked league-wide (not per-league -- see top_performers_service.py's
    DEFAULT_SCORING ranking) for the dashboard's Top Performers panel.
    One row per (week, year), NFL-wide rather than scoped to any one
    league (there's no league_id here at all -- unlike CommissionerDigest/
    TeamWeeklyRecap). Auto-generated by the scheduler once a week goes
    final; no manual "commissioner" exists for a global panel, so the
    generate endpoint is open to any authenticated user as a fallback,
    same rate-limit shape as everything else in ai.py."""
    __tablename__ = "weekly_top_players_summaries"
    __table_args__ = (
        UniqueConstraint("week", "year", name="uq_weekly_top_players_summary_week_year"),
    )

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    week: Mapped[int] = mapped_column(Integer, nullable=False)
    year: Mapped[int] = mapped_column(Integer, nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    # Top N players (name/position/team/points), stored alongside the
    # prose summary so the dashboard can render a real ranked list next
    # to the AI text without re-deriving it or re-querying Player.
    top_players: Mapped[list] = mapped_column(MutableList.as_mutable(JSON), nullable=False, default=list)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
