import uuid
from datetime import datetime
from sqlalchemy import String, Integer, Text, DateTime, func, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from app.core.database import Base


class WeeklyScoresRecap(Base):
    """AI-generated (sarcastic-tone) recap of the week's real NFL games,
    for the dashboard's NFL Scores panel -- see nfl_schedule_service.py
    for where the underlying NFLGame rows come from (ESPN's public
    scoreboard). One row per (week, year), NFL-wide like
    WeeklyTopPlayersSummary. Auto-generated by the scheduler once a week
    goes final."""
    __tablename__ = "weekly_scores_recaps"
    __table_args__ = (
        UniqueConstraint("week", "year", name="uq_weekly_scores_recap_week_year"),
    )

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    week: Mapped[int] = mapped_column(Integer, nullable=False)
    year: Mapped[int] = mapped_column(Integer, nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
