"""
Dashboard AI Summaries -- NFL-wide (not per-league) panels: top real
NFL performers this week, and a funny recap of this week's real NFL
games. Both auto-generated by the scheduler once a week goes final
(see scheduler.py's week-transition hook); the POST endpoints here are
just the manual fallback (e.g. the very first week after this ships,
before any scheduler tick has fired, or if a scheduler pass ever
fails) -- open to any authenticated user rather than commissioner-gated,
since there's no "commissioner" of a global, not-per-league panel.
Rate-limited per-IP for abuse protection; no per-league AI-usage budget
applies here (that's a per-league concept) since a single generation
serves every viewer -- a cached GET has zero marginal LLM cost no
matter how many people load the dashboard.
"""
from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.core.database import get_db
from app.core.limiter import limiter
from app.models.user import User
from app.models.nfl_game import NFLGame
from app.models.weekly_top_players_summary import WeeklyTopPlayersSummary
from app.models.weekly_scores_recap import WeeklyScoresRecap
from app.api.deps import get_current_user
from app.services import top_performers_service, nfl_schedule_service
from app.services.ai_service import AIService
from app.core.config import settings

router = APIRouter(prefix="/dashboard", tags=["dashboard"])


def _get_ai_service() -> AIService:
    if settings.OPENAI_API_KEY:
        return AIService(api_key=settings.OPENAI_API_KEY, provider="openai")
    if settings.ANTHROPIC_API_KEY:
        return AIService(api_key=settings.ANTHROPIC_API_KEY, provider="anthropic")
    return AIService(api_key=None)


@router.get("/top-performers")
async def get_top_performers(db: AsyncSession = Depends(get_db)):
    """The most recently generated summary -- no week/year params:
    this is an ambient "what's current" panel, not something a viewer
    browses historically (unlike the per-league Digest)."""
    result = await db.execute(
        select(WeeklyTopPlayersSummary).order_by(
            WeeklyTopPlayersSummary.year.desc(), WeeklyTopPlayersSummary.week.desc(),
        ).limit(1)
    )
    summary = result.scalar_one_or_none()
    if not summary:
        raise HTTPException(status_code=404, detail="No top-performers summary generated yet")
    return {
        "week": summary.week, "year": summary.year, "content": summary.content,
        "top_players": summary.top_players, "created_at": summary.created_at,
    }


@router.post("/top-performers/generate")
@limiter.limit("10/hour")
async def generate_top_performers(
    request: Request,
    week: int,
    year: int,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Manual fallback -- see module docstring. Same shape as the
    scheduler's own auto-generation call."""
    summary = await top_performers_service.generate_and_save_summary(week, year, db)
    return {
        "week": summary.week, "year": summary.year, "content": summary.content,
        "top_players": summary.top_players, "created_at": summary.created_at,
    }


@router.get("/nfl-scores")
async def get_nfl_scores(db: AsyncSession = Depends(get_db)):
    """Most recently synced week's games + that week's recap (if
    generated yet -- games can exist before the recap does, e.g. right
    after a sync but before the scheduler's recap-generation step)."""
    latest_game = await db.execute(select(NFLGame).order_by(NFLGame.year.desc(), NFLGame.week.desc()).limit(1))
    latest = latest_game.scalar_one_or_none()
    if not latest:
        raise HTTPException(status_code=404, detail="No NFL game data synced yet")

    games_result = await db.execute(
        select(NFLGame).where(
            NFLGame.year == latest.year, NFLGame.week == latest.week, NFLGame.season_type == latest.season_type,
        ).order_by(NFLGame.kickoff_at)
    )
    games = games_result.scalars().all()

    recap_result = await db.execute(
        select(WeeklyScoresRecap).where(
            WeeklyScoresRecap.week == latest.week, WeeklyScoresRecap.year == latest.year,
        )
    )
    recap = recap_result.scalar_one_or_none()

    return {
        "week": latest.week, "year": latest.year, "season_type": latest.season_type,
        "games": [
            {
                "home_team": g.home_team, "home_team_name": g.home_team_name, "home_score": g.home_score,
                "away_team": g.away_team, "away_team_name": g.away_team_name, "away_score": g.away_score,
                "status_detail": g.status_detail, "completed": g.completed, "kickoff_at": g.kickoff_at,
            }
            for g in games
        ],
        "recap": recap.content if recap else None,
    }


@router.post("/nfl-scores/generate")
@limiter.limit("10/hour")
async def generate_nfl_scores(
    request: Request,
    week: int,
    year: int,
    season_type: int = 2,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Manual fallback -- syncs fresh games from ESPN, then generates
    the recap from them, same two-step the scheduler's own
    auto-generation hook does."""
    await nfl_schedule_service.sync_week_scoreboard(year, week, season_type, db)
    games = await nfl_schedule_service.get_week_games(year, week, season_type, db)
    if not games:
        raise HTTPException(status_code=404, detail="No games found for that week")

    games_payload = [
        {
            "home_team_name": g.home_team_name, "home_score": g.home_score,
            "away_team_name": g.away_team_name, "away_score": g.away_score,
            "completed": g.completed, "status_detail": g.status_detail,
        }
        for g in games
    ]
    service = _get_ai_service()
    content = await service.generate_nfl_scores_recap(week=week, year=year, games=games_payload)

    existing = await db.execute(
        select(WeeklyScoresRecap).where(WeeklyScoresRecap.week == week, WeeklyScoresRecap.year == year)
    )
    recap = existing.scalar_one_or_none()
    if recap:
        recap.content = content
    else:
        recap = WeeklyScoresRecap(week=week, year=year, content=content)
        db.add(recap)
    await db.commit()

    return {"week": week, "year": year, "content": content}
