import Link from "next/link";
import LegalPageLayout, { LegalSection } from "@/components/LegalPageLayout";

export default function TermsOfServicePage() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="August 11, 2026">
      <LegalSection heading="Agreement">
        <p>
          By creating an account or using FantasyFootballCrew, you agree to these terms. If you
          don&apos;t agree with them, please don&apos;t use the platform.
        </p>
      </LegalSection>

      <LegalSection heading="What this is">
        <p>
          FantasyFootballCrew is a free, currently-in-beta fantasy football platform: custom
          scoring, drafts, trades, waivers, standings, and AI-powered analysis tools. Features may
          change, break, or be removed as the platform develops — that&apos;s what beta means.
        </p>
      </LegalSection>

      <LegalSection heading="No real-money play">
        <p>
          FantasyFootballCrew does not process payments, collect entry fees, pay out prizes, or
          facilitate wagering of any kind. It&apos;s a platform for running fantasy football
          leagues among people who already know each other — anything your league does with real
          money is between you and your leaguemates, entirely outside this platform and outside
          these terms.
        </p>
      </LegalSection>

      <LegalSection heading="Your account">
        <p>
          You&apos;re responsible for the activity on your account and for keeping your password
          secure. Give us accurate registration info. You must be at least 13 years old to create
          an account.
        </p>
      </LegalSection>

      <LegalSection heading="Acceptable use">
        <p>You agree not to:</p>
        <ul className="list-disc list-inside space-y-1.5 marker:text-surface-600">
          <li>Attempt to break, exploit, or abuse the platform or its scoring logic</li>
          <li>Scrape, automate, or hammer the service outside of normal use</li>
          <li>Impersonate another person or misrepresent your affiliation with anyone</li>
          <li>Use the platform for anything illegal, or to harass or abuse other users</li>
        </ul>
      </LegalSection>

      <LegalSection heading="Your content">
        <p>
          League names, team names, and anything else you create on the platform are yours. You&apos;re
          responsible for what you post — keep it legal and don&apos;t harass other users.
        </p>
      </LegalSection>

      <LegalSection heading="AI features">
        <p>
          The AI Analysis tools (lineup suggestions, trade evaluations, matchup takes) are
          generated by a third-party AI model and are meant as a fun, informational starting
          point — not professional or guaranteed-accurate advice. Use your own judgment for actual
          lineup and trade decisions.
        </p>
      </LegalSection>

      <LegalSection heading="The service is provided as-is">
        <p>
          FantasyFootballCrew is provided &quot;as is&quot; and &quot;as available,&quot; without
          warranties of any kind. We don&apos;t guarantee the service will be uninterrupted,
          error-free, or available at all times — especially during beta. To the fullest extent the
          law allows, we&apos;re not liable for any indirect, incidental, or consequential damages
          arising from your use of the platform.
        </p>
      </LegalSection>

      <LegalSection heading="Termination">
        <p>
          We can suspend or terminate accounts that violate these terms, particularly the
          acceptable-use section above. You can stop using the platform at any time; see the{" "}
          <Link href="/privacy" className="text-gold-400 hover:text-gold-300">
            Privacy Policy
          </Link>{" "}
          for how to request your data be deleted.
        </p>
      </LegalSection>

      <LegalSection heading="Changes to these terms">
        <p>
          If these terms change in a meaningful way, we&apos;ll update the date at the top of this
          page.
        </p>
      </LegalSection>

      <LegalSection heading="Contact">
        <p>
          Questions about these terms:{" "}
          <a href="mailto:djk8286@gmail.com" className="text-gold-400 hover:text-gold-300">
            djk8286@gmail.com
          </a>
        </p>
      </LegalSection>
    </LegalPageLayout>
  );
}
