"""add league visibility

Revision ID: 3fe38bc9ecc9
Revises: 90f2ae719677
Create Date: 2026-08-12 21:07:34.422063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe38bc9ecc9'
down_revision: Union[str, Sequence[str], None] = '90f2ae719677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default is required here (autogenerate doesn't add one on its
    # own) -- these are NOT NULL columns being added to the existing
    # `leagues` table, which already has real rows in production. Without
    # a server-side default, ALTER TABLE ADD COLUMN NOT NULL fails outright
    # against any table with existing data. 'OPEN'/false match the model's
    # Python-level defaults (League.visibility/wanted_board_hidden) --
    # every pre-existing league keeps behaving exactly as "Open, not
    # hidden" until a commissioner deliberately changes it.
    op.add_column('leagues', sa.Column('visibility', sa.Enum('PRIVATE', 'INVITE_ONLY', 'OPEN', name='leaguevisibility'), nullable=False, server_default='OPEN'))
    op.add_column('leagues', sa.Column('wanted_board_hidden', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'wanted_board_hidden')
    op.drop_column('leagues', 'visibility')
    # ### end Alembic commands ###
