"""one active draft per league

Revision ID: 4cb1bc348459
Revises: f8b382aa77e8
Create Date: 2026-08-11 16:14:11.733878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb1bc348459'
down_revision: Union[str, Sequence[str], None] = 'f8b382aa77e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_drafts_one_active_per_league', 'drafts', ['league_id'], unique=True, postgresql_where=sa.text("status != 'COMPLETED'"), sqlite_where=sa.text("status != 'COMPLETED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_drafts_one_active_per_league', table_name='drafts', postgresql_where=sa.text("status != 'COMPLETED'"), sqlite_where=sa.text("status != 'COMPLETED'"))
    # ### end Alembic commands ###
