"""add league invites

Revision ID: 57102c922ca0
Revises: 3fe38bc9ecc9
Create Date: 2026-08-12 21:43:07.661007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57102c922ca0'
down_revision: Union[str, Sequence[str], None] = '3fe38bc9ecc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Unlike the ADD COLUMN case in 3fe38bc9ecc9 (which needed the
    # 'leaguevisibility' enum type created explicitly first), this is a
    # brand new CREATE TABLE -- Postgres' DDL compiler auto-emits CREATE
    # TYPE for an inline Enum column as part of CREATE TABLE, so
    # 'invitestatus' doesn't need the same explicit .create() treatment.
    # created_at's server_default swapped from autogenerate's SQLite-
    # dialect sa.text('(CURRENT_TIMESTAMP)') to the portable sa.func.now()
    # -- the same fix every migration this project has needed one.
    op.create_table('league_invites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('invited_email', sa.String(), nullable=False),
    sa.Column('invited_by_user_id', sa.String(), nullable=False),
    sa.Column('personal_message', sa.Text(), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', name='invitestatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_invites_invited_email'), 'league_invites', ['invited_email'], unique=False)
    op.create_index(op.f('ix_league_invites_league_id'), 'league_invites', ['league_id'], unique=False)
    op.create_index(op.f('ix_league_invites_token_hash'), 'league_invites', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_league_invites_token_hash'), table_name='league_invites')
    op.drop_index(op.f('ix_league_invites_league_id'), table_name='league_invites')
    op.drop_index(op.f('ix_league_invites_invited_email'), table_name='league_invites')
    op.drop_table('league_invites')
    # ### end Alembic commands ###
