"""add playoffs

Revision ID: 90f2ae719677
Revises: ff739e020b40
Create Date: 2026-08-12 15:17:42.007488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f2ae719677'
down_revision: Union[str, Sequence[str], None] = 'ff739e020b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playoffs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seeding_method', sa.String(), nullable=False),
    sa.Column('conference_bracket_mode', sa.String(), nullable=True),
    sa.Column('seeds', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='playoffstatus'), nullable=False),
    sa.Column('start_week', sa.Integer(), nullable=False),
    sa.Column('total_rounds', sa.Integer(), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'year', name='uq_playoff_league_year')
    )
    op.create_table('playoff_matchups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('playoff_id', sa.String(), nullable=False),
    sa.Column('bracket', sa.String(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sa.String(), nullable=True),
    sa.Column('team_b_id', sa.String(), nullable=True),
    sa.Column('is_bye', sa.Boolean(), nullable=False),
    sa.Column('winner_team_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['playoff_id'], ['playoffs.id'], ),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('leagues', sa.Column('playoff_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'playoff_settings')
    op.drop_table('playoff_matchups')
    op.drop_table('playoffs')
    # ### end Alembic commands ###
