"""add league join requests

Revision ID: b136ce50878b
Revises: 57102c922ca0
Create Date: 2026-08-12 22:02:14.739795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b136ce50878b'
down_revision: Union[str, Sequence[str], None] = '57102c922ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # A brand new CREATE TABLE -- like 57102c922ca0's league_invites, the
    # inline Enum('joinrequeststatus') auto-creates via Postgres' DDL
    # compiler, no explicit .create() needed (only ADD COLUMN needs that,
    # per 3fe38bc9ecc9). created_at's server_default swapped from
    # autogenerate's SQLite-dialect sa.text('(CURRENT_TIMESTAMP)') to the
    # portable sa.func.now().
    op.create_table('league_join_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('requested_by_user_id', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', name='joinrequeststatus'), nullable=False),
    sa.Column('decided_by_user_id', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_join_requests_league_id'), 'league_join_requests', ['league_id'], unique=False)
    op.create_index(op.f('ix_league_join_requests_requested_by_user_id'), 'league_join_requests', ['requested_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_league_join_requests_requested_by_user_id'), table_name='league_join_requests')
    op.drop_index(op.f('ix_league_join_requests_league_id'), table_name='league_join_requests')
    op.drop_table('league_join_requests')
    # ### end Alembic commands ###
