"""baseline: schema as of Alembic adoption

Every table/column/index/FK as of Alembic's adoption into this project --
this is what a brand new environment (a fresh clone, a new Postgres
instance) bootstraps from from via `alembic upgrade head`. Both the
existing local SQLite db (ffc.db) and production Postgres already have
this exact schema (built up via the hand-rolled migrate_add_*.py
scripts this replaces) -- they get `alembic stamp head` instead of
actually running this, which just records "already here" without
touching any table. See DEPLOYMENT.md for the full adoption story.

Autogenerated against an empty Postgres db (matches production, the
dialect that actually matters), then hand-edited: autogenerate baked
every created_at/updated_at server_default in as a literal
`sa.text('now()')` -- Postgres-specific, and SQLite silently accepts
it in CREATE TABLE but then throws `unknown function: now()` on the
first actual insert (confirmed by testing, not assumed). Swapped every
occurrence for `sa.func.now()`, the portable SQLAlchemy construct the
models themselves already use (see e.g. Team.created_at) -- it compiles
to each dialect's own spelling (now() / CURRENT_TIMESTAMP) at the
point a migration actually runs, instead of a string frozen at
generation time under whichever one dialect happened to be connected.
Re-verified end-to-end against fresh Postgres and fresh SQLite after
the edit, including a real insert (not just CREATE TABLE, which
doesn't validate the default expression on either dialect).

Revision ID: f8b382aa77e8
Revises:
Create Date: 2026-08-11 14:57:58.816472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b382aa77e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sleeper_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('bye_week', sa.Integer(), nullable=True),
    sa.Column('injury_status', sa.String(), nullable=True),
    sa.Column('fantasy_positions', sa.JSON(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('stats_year', sa.Integer(), nullable=True),
    sa.Column('week_stats', sa.JSON(), nullable=True),
    sa.Column('last_season_stats', sa.JSON(), nullable=True),
    sa.Column('last_season_year', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_sleeper_id'), 'players', ['sleeper_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('leagues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('commissioner_id', sa.String(), nullable=False),
    sa.Column('league_type', sa.Enum('STANDARD', 'TWO_MAN', 'CONFERENCE', name='leaguetype'), nullable=False),
    sa.Column('scoring_config', sa.JSON(), nullable=True),
    sa.Column('max_teams', sa.Integer(), nullable=False),
    sa.Column('draft_status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='draftstatus'), nullable=False),
    sa.Column('draft_type', sa.Enum('SNAKE', 'AUCTION', name='drafttype'), nullable=False),
    sa.Column('draft_order', sa.JSON(), nullable=True),
    sa.Column('waiver_priority', sa.JSON(), nullable=True),
    sa.Column('co_commissioner_ids', sa.JSON(), nullable=True),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['commissioner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='draftrunstatus'), nullable=False),
    sa.Column('draft_type', sa.String(), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('current_pick', sa.Integer(), nullable=False),
    sa.Column('total_rounds', sa.Integer(), nullable=False),
    sa.Column('team_order', sa.String(), nullable=True),
    sa.Column('timer_seconds', sa.Integer(), nullable=False),
    sa.Column('current_pick_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoring_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('stat_name', sa.String(), nullable=False),
    sa.Column('points_per_unit', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('co_owner_id', sa.String(), nullable=True),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_cpu', sa.Boolean(), nullable=False),
    sa.Column('conference', sa.String(), nullable=True),
    sa.Column('roster', sa.JSON(), nullable=True),
    sa.Column('roster_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('ties', sa.Integer(), nullable=False),
    sa.Column('points_for', sa.Float(), nullable=False),
    sa.Column('points_against', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['co_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coaches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Enum('HC', 'OC', 'DC', 'STC', name='coachposition'), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('bonus_type', sa.String(), nullable=True),
    sa.Column('bonus_value', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_picks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('draft_id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('pick_number', sa.Integer(), nullable=False),
    sa.Column('drafted_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_adjustments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('TRADE', 'WAIVER', 'ADD', 'DROP', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', name='transactionstatus'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('projected_score', sa.Float(), nullable=True),
    sa.Column('lineup_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'team_id', 'week', 'year', name='uq_weekly_score')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_scores')
    op.drop_table('transactions')
    op.drop_table('score_adjustments')
    op.drop_table('draft_picks')
    op.drop_table('coaches')
    op.drop_table('teams')
    op.drop_table('scoring_configs')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_players_sleeper_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
